// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: cleaner.proto

package cleaner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId     uint64 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Priority     uint32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	CleaningType uint32 `protobuf:"varint,4,opt,name=cleaning_type,json=cleaningType,proto3" json:"cleaning_type,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cleaner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_cleaner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_cleaner_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Request) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Request) GetCleaningType() uint32 {
	if x != nil {
		return x.CleaningType
	}
	return 0
}

type ProceedCleaningIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req    *Request `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	TeamId uint64   `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *ProceedCleaningIn) Reset() {
	*x = ProceedCleaningIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cleaner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProceedCleaningIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProceedCleaningIn) ProtoMessage() {}

func (x *ProceedCleaningIn) ProtoReflect() protoreflect.Message {
	mi := &file_cleaner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProceedCleaningIn.ProtoReflect.Descriptor instead.
func (*ProceedCleaningIn) Descriptor() ([]byte, []int) {
	return file_cleaner_proto_rawDescGZIP(), []int{1}
}

func (x *ProceedCleaningIn) GetReq() *Request {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *ProceedCleaningIn) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type ProceedCleaningOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration string `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *ProceedCleaningOut) Reset() {
	*x = ProceedCleaningOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cleaner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProceedCleaningOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProceedCleaningOut) ProtoMessage() {}

func (x *ProceedCleaningOut) ProtoReflect() protoreflect.Message {
	mi := &file_cleaner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProceedCleaningOut.ProtoReflect.Descriptor instead.
func (*ProceedCleaningOut) Descriptor() ([]byte, []int) {
	return file_cleaner_proto_rawDescGZIP(), []int{2}
}

func (x *ProceedCleaningOut) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

type GetAvailableTeamsIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAvailableTeamsIn) Reset() {
	*x = GetAvailableTeamsIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cleaner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableTeamsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableTeamsIn) ProtoMessage() {}

func (x *GetAvailableTeamsIn) ProtoReflect() protoreflect.Message {
	mi := &file_cleaner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableTeamsIn.ProtoReflect.Descriptor instead.
func (*GetAvailableTeamsIn) Descriptor() ([]byte, []int) {
	return file_cleaner_proto_rawDescGZIP(), []int{3}
}

type GetAvailableTeamsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamsIds []uint64 `protobuf:"varint,1,rep,packed,name=teams_ids,json=teamsIds,proto3" json:"teams_ids,omitempty"`
}

func (x *GetAvailableTeamsOut) Reset() {
	*x = GetAvailableTeamsOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cleaner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvailableTeamsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableTeamsOut) ProtoMessage() {}

func (x *GetAvailableTeamsOut) ProtoReflect() protoreflect.Message {
	mi := &file_cleaner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableTeamsOut.ProtoReflect.Descriptor instead.
func (*GetAvailableTeamsOut) Descriptor() ([]byte, []int) {
	return file_cleaner_proto_rawDescGZIP(), []int{4}
}

func (x *GetAvailableTeamsOut) GetTeamsIds() []uint64 {
	if x != nil {
		return x.TeamsIds
	}
	return nil
}

var File_cleaner_proto protoreflect.FileDescriptor

var file_cleaner_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x65, 0x72, 0x22, 0x77, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d,
	0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x50, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x43, 0x6c, 0x65, 0x61,
	0x6e, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65,
	0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x65, 0x61,
	0x6d, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x43, 0x6c,
	0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x49, 0x6e, 0x22, 0x33, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d,
	0x73, 0x4f, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x49, 0x64,
	0x73, 0x32, 0xae, 0x01, 0x0a, 0x0e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x43,
	0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x65,
	0x72, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x65, 0x64, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e,
	0x67, 0x49, 0x6e, 0x1a, 0x1b, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x65, 0x72, 0x2e, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x65, 0x64, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x75, 0x74,
	0x12, 0x50, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x62, 0x61, 0x6c, 0x65,
	0x54, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x1c, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d,
	0x73, 0x49, 0x6e, 0x1a, 0x1d, 0x2e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x4f,
	0x75, 0x74, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x42, 0x61, 0x7a, 0x68, 0x65, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x6c, 0x65, 0x61,
	0x6e, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cleaner_proto_rawDescOnce sync.Once
	file_cleaner_proto_rawDescData = file_cleaner_proto_rawDesc
)

func file_cleaner_proto_rawDescGZIP() []byte {
	file_cleaner_proto_rawDescOnce.Do(func() {
		file_cleaner_proto_rawDescData = protoimpl.X.CompressGZIP(file_cleaner_proto_rawDescData)
	})
	return file_cleaner_proto_rawDescData
}

var file_cleaner_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cleaner_proto_goTypes = []interface{}{
	(*Request)(nil),              // 0: cleaner.Request
	(*ProceedCleaningIn)(nil),    // 1: cleaner.ProceedCleaningIn
	(*ProceedCleaningOut)(nil),   // 2: cleaner.ProceedCleaningOut
	(*GetAvailableTeamsIn)(nil),  // 3: cleaner.GetAvailableTeamsIn
	(*GetAvailableTeamsOut)(nil), // 4: cleaner.GetAvailableTeamsOut
}
var file_cleaner_proto_depIdxs = []int32{
	0, // 0: cleaner.ProceedCleaningIn.req:type_name -> cleaner.Request
	1, // 1: cleaner.CleanerService.ProceedCleaning:input_type -> cleaner.ProceedCleaningIn
	3, // 2: cleaner.CleanerService.GetAvailbaleTeams:input_type -> cleaner.GetAvailableTeamsIn
	2, // 3: cleaner.CleanerService.ProceedCleaning:output_type -> cleaner.ProceedCleaningOut
	4, // 4: cleaner.CleanerService.GetAvailbaleTeams:output_type -> cleaner.GetAvailableTeamsOut
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cleaner_proto_init() }
func file_cleaner_proto_init() {
	if File_cleaner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cleaner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cleaner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProceedCleaningIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cleaner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProceedCleaningOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cleaner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailableTeamsIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cleaner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvailableTeamsOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cleaner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cleaner_proto_goTypes,
		DependencyIndexes: file_cleaner_proto_depIdxs,
		MessageInfos:      file_cleaner_proto_msgTypes,
	}.Build()
	File_cleaner_proto = out.File
	file_cleaner_proto_rawDesc = nil
	file_cleaner_proto_goTypes = nil
	file_cleaner_proto_depIdxs = nil
}
